services:
  webview:
    build: ./src/webview/

  customer_api:
    build: ./src/customer_api/
    ports:
      - "8080:8000"
    develop:
      watch:
        - action: rebuild
          path: ./src/customer_api/target/debug/customer_api
          target: ./src/customer_api/target/debug/

  machine_api:
    build: ./src/machine_api/
    develop:
      watch:
        - action: rebuild
          path: ./src/machine_api/target/debug/machine_api
          target: ./src/machine_api/target/debug/

  database:
    build: ./src/database/
    env_file: ./src/database/database.env
    # volumes:
    #   database-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webview:
    build: ./src/webview/

# volumes:
#   database-volume:
