---
apiVersion: v1
kind: Service 
metadata:
  name: sp-database-service
  labels:
    app: sp-database
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: sp-database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sp-database-ss
  labels:
    app: sp-database
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: sp-database
  template:
    metadata:
      labels:
        app: sp-database
    spec:
      containers:
      - name: sp-database-cont
        image: jarnstrom/sp_database:latest
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: sp-database-data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sp-credentials
              key: postgres-password
        - name: SP_CUSTOMER_USER
          valueFrom:
            secretKeyRef:
              name: sp-credentials
              key: customer-username
        - name: SP_CUSTOMER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sp-credentials
              key: customer-password
        - name: SP_CUSTOMER_DATABASE
          valueFrom:
            configMapKeyRef:
              name: sp-config
              key: customer-db-name
        - name: SP_MACHINE_USER
          valueFrom:
            secretKeyRef:
              name: sp-credentials
              key: machine-username
        - name: SP_MACHINE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sp-credentials
              key: machine-password
        - name: SP_MACHINE_DATABASE
          valueFrom:
            configMapKeyRef:
              name: sp-config
              key: machine-db-name
  volumeClaimTemplates:
    - metadata:
        name: sp-database-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Mi
---

