---
apiVersion: v1
kind: Service 
metadata:
  name: sp-machine-service
  labels:
    app: sp-machine-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: sp-machine-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-machine-dep
  labels:
    app: sp-machine-api
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: sp-machine-api
  template:
    metadata:
      labels:
        app: sp-machine-api
    spec:
      containers:
        - name: sp-machine-api-cont
          image: jarnstrom/sp_machine_api:latest
          ports:
            - containerPort: 8000
          env:
          - name: SP_DB_PASS
            valueFrom:
              secretKeyRef:
                name: sp-credentials
                key: machine-password
          - name: SP_DB_USER
            valueFrom:
              secretKeyRef:
                name: sp-credentials
                key: machine-username
          - name: SP_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: sp-config
                key: machine-db-name
          - name: SP_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: sp-config
                key: database-host
---

