---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sp-config
  labels:
    data: config 
data:
  customer-db-name: "sp_customer_db"
  machine-db-name: "sp_machine_db"
  database-host: "sp-database-service"
  customer-host: "sp-customer-service"
  machine-host: "sp-machine-service"
---
