[package]
name = "customer_api"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = { version = "0.4.2", features = ["server"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
